### ISSUE TITLE
paquete mindicador

### ISSUE THREAD

**Issue by jbkunst** [DCCP-Hugo/MercadoPublicoOCDS#3]
Hola,

Solamente quería hacer notar que existe el paquete mindicador https://github.com/pachamaltese/mindicador para ahorrarte un par de líneas en https://github.com/DCCP-Hugo/MercadoPublicoOCDS/blob/c4bdda44a474a5d13eb544e5c7fd7fefa86245bd/Extraccion.R#L365

Saludos!

**Comment by DCCP-Hugo** [comment]
Está interesante, y bastante intuitiva en formato paquete.
Muchas gracias.
